package nezet;

import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modell.Konfiguracio;

public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbSzak = new javax.swing.JComboBox<>();
        chbHirlevel = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPrgBetoltes = new javax.swing.JMenuItem();
        mnuPrgMentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPrgKilepes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aktualis Konfiguracio"));

        jLabel1.setText("Név");

        jLabel2.setText("Szak");

        cmbSzak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--== Kiválasztott szak ==--", "Szoftverfejlesztő", "Rendszergazda", "Szoftverfejlesztő és tesztelő" }));

        chbHirlevel.setSelected(true);
        chbHirlevel.setText("hírlevél");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbHirlevel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbHirlevel)
                    .addComponent(cmbSzak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jMenu1.setText("Konfiguracio");

        mnuPrgBetoltes.setText("Betöltés...");
        mnuPrgBetoltes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgBetoltesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgBetoltes);

        mnuPrgMentes.setText("Mentés...");
        mnuPrgMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgMentesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgMentes);
        jMenu1.add(jSeparator1);

        mnuPrgKilepes.setText("Kilépés...");
        mnuPrgKilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgKilepesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPrgKilepes);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Program");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jMenu4.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPrgKilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgKilepesActionPerformed
        kilepes();
    }//GEN-LAST:event_mnuPrgKilepesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //System.out.println("kilépés folyamatban...");
        kilepes();
    }//GEN-LAST:event_formWindowClosing

    private void mnuPrgMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgMentesActionPerformed
        //JFileChooser jfc = new JFileChooser();//Documents könnyvtár
        String hely = System.getProperty("user.dir");
        JFileChooser jfc = new JFileChooser(hely);//aktuális projekt könnyvtár
        
        /* jfc paraméterezése: */
        File kivalasztottFajl = new File(hely + "\\" + txtNev.getText() + ".txt");
        System.out.println("fajl = " + kivalasztottFajl);
        jfc.setSelectedFile(kivalasztottFajl);
        
        /* jfc megjelenítése, vizsgálata */
        int gomb = jfc.showSaveDialog(rootPane);//null | this <-- ez ua, mint rootPane
        
        if (gomb == JFileChooser.APPROVE_OPTION) {
            kivalasztottFajl = jfc.getSelectedFile();
            String fajlElerese = kivalasztottFajl.getAbsolutePath();
            Path path = Path.of(fajlElerese);//hova írjuk
            try {
                Files.writeString(path, tartalom());
            } catch (IOException ex) {
                /* felhasználónak: */
                String msg = "IO hiba!\n" + ex.getMessage();
                JOptionPane.showMessageDialog(rootPane, msg);
                /* fejlesztőnek: */
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        /* a mentés alapszerkezete: */
//        Path path = Path.of("kimenet.txt");//hova írjuk
//        byte[] bytes = jTextField1.getText().getBytes();//mit írunk
//        try {
//            //Files.write(path, bytes);
//            Files.writeString(path, jTextField1.getText());
//        } catch (IOException ex) {// generált kód!!!
//            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_mnuPrgMentesActionPerformed

    private void mnuPrgBetoltesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgBetoltesActionPerformed
        /* a beolvasás alapszerkezete: */
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));//aktuális projekt könnyvtár
        int gomb = jfc.showSaveDialog(rootPane);//null | this <-- ez ua, mint rootPane
        if (gomb == JFileChooser.APPROVE_OPTION) {
            File kivalasztottFajl = jfc.getSelectedFile();
            try {
                String egySor = Files.readString(kivalasztottFajl.toPath());
                System.out.println("A beolvasott fájl tartalma: ");
                System.out.println(egySor);
                
                //modell létrehozasa
                //Konfiguracio modell =new Konfiguracio(nev,index,chb);
                Konfiguracio modell =new Konfiguracio(egySor);
                        
                //modell felhasznalasa
                txtNev.setText(modell.getNev());
                cmbSzak.setSelectedIndex(modell.getIndex());
                chbHirlevel.setSelected(modell.isHirlevel());
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuPrgBetoltesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNev.setText(" ");
        cmbSzak.setSelectedIndex(0);
        chbHirlevel.setSelected(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private String tartalom(){
        String nev = txtNev.getText();
        //String szak = cmbSzak.getSelectedItem().toString();
        int index = cmbSzak.getSelectedIndex();
        boolean hirlevel = chbHirlevel.isSelected();
        final String SEP = " ";
        return nev+SEP+index+SEP+hirlevel;
//        String msg = "név: " + nev
//                +"\nszak: %s(%d)".formatted(szak, cmbSzak.getSelectedIndex())
//                +"\nhírlevél: " + (hirlevel?"kér":"nem kér");
//        return msg;
    }
    private void kilepes() throws HeadlessException {
        String msg = "Biztos kilépsz?";
        String cim = "KILÉPÉS";
        int msgTip = JOptionPane.QUESTION_MESSAGE;
        int optTip = JOptionPane.YES_NO_OPTION;//.OK_CANCEL_OPTION;
        //JOptionPane.showMessageDialog(this, msg, cim, msgTip);
        int gomb = JOptionPane.showConfirmDialog(rootPane, msg, cim, optTip);
        if (gomb == JOptionPane.YES_OPTION) {
            int hibaKod = 0;
            System.exit(hibaKod);
        }
        
        //System.out.println("gomb = " + gomb);//YES: 0, NO: 1 , X: -1
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbHirlevel;
    private javax.swing.JComboBox<String> cmbSzak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuPrgBetoltes;
    private javax.swing.JMenuItem mnuPrgKilepes;
    private javax.swing.JMenuItem mnuPrgMentes;
    private javax.swing.JTextField txtNev;
    // End of variables declaration//GEN-END:variables
}
